{% set name = "python-openstackclient" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 078e7bde08acfa0d2110987c187f8e3abdd03057fc552bec8b83deba6a1a8f2b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openstack = openstackclient.shell:main

requirements:
  host:
    - pbr
    - pip
    - python >3
    - setuptools
  run:
    - babel
    - jsonschema
    - keystoneauth1
    - msgpack-python
    - openstacksdk
    - osc-lib
    - oslo.i18n
    - oslo.utils
    - python >3
    - python-cinderclient
    - python-glanceclient
    - python-keystoneclient
    - python-novaclient
    - setuptools
    - six

test:
  imports:
    - openstackclient
  commands:
    - openstack --help


about:
  home: https://docs.openstack.org/python-openstackclient/latest/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Client for OpenStack services
  doc_url: https://docs.openstack.org/python-openstackclient/latest/
  dev_url: https://opendev.org/openstack/python-openstackclient

extra:
  recipe-maintainers:
    - tschoonj
